import warnings
from functools import wraps
from pathlib import Path

from .paradox_lib import ParadoxHelper, ParadoxLocWriter
from .paths import commons, localization


def handler(folder_path, filename, yml=False):
    def decorator(func):
        @wraps(func)
        def wrapper(self):
            content = func(self)
            base = localization if yml else commons
            folder = folder_path(base) if callable(folder_path) else folder_path
            return [folder, content, filename, yml]

        if not hasattr(func, '_is_handler'):
            func._is_handler = True
            func._wrapper = wrapper
            func._folder_path = folder_path
            func._filename = filename
            func._yml = yml

        return func
    return decorator


class HandlerMeta(type):
    _global_file_registry = {}

    def __new__(mcs, name, bases, namespace):
        cls = super().__new__(mcs, name, bases, namespace)

        handlers = []
        for attr_name in dir(cls):
            attr = getattr(cls, attr_name)
            if hasattr(attr, '_is_handler') and hasattr(attr, '_wrapper'):
                handlers.append(attr._wrapper)

                folder_path = attr._folder_path
                filename = attr._filename

                if callable(folder_path):
                    file_key = f"<dynamic>/{filename}"
                else:
                    file_key = str(Path(folder_path) / filename)

                if file_key in mcs._global_file_registry:
                    previous_class, previous_method = mcs._global_file_registry[file_key]
                    warnings.warn(
                        f"\n⚠️  DUPLICATE OUTPUT FILE DETECTED ⚠️\n"
                        f"File: {filename}\n"
                        f"Folder: {folder_path}\n"
                        f"First defined in: {previous_class}.{previous_method}()\n"
                        f"Also defined in: {name}.{attr_name}()\n"
                        f"The second handler will OVERWRITE the first!\n",
                        UserWarning,
                        stacklevel=2
                    )
                else:
                    mcs._global_file_registry[file_key] = (name, attr_name)

        cls.handlers = handlers
        return cls


class BaseHandler(metaclass=HandlerMeta):
    def __init__(self, files):
        self.parse_and_update(files)

    def parse_and_update(self, files):
        self.trees = [ParadoxHelper.parse_file(file) for file in files]

        paradox_outputs = []
        yml_outputs = []

        for handler_wrapper in self.handlers:
            result = handler_wrapper(self)
            if result:
                folder, content, filename, is_yml = result
                if is_yml:
                    yml_outputs.append((folder, content, filename))
                else:
                    paradox_outputs.append((folder, content, filename))

        if paradox_outputs:
            ParadoxHelper.write_handled_files(*paradox_outputs)

        if yml_outputs:
            BaseHandler._write_yml_files(*yml_outputs)

    @staticmethod
    def _write_yml_files(*file_data):
        writer = ParadoxLocWriter()
        for folder, content, filename in file_data:
            folder.mkdir(parents=True, exist_ok=True)
            filepath = folder / filename
            yml_text = writer.write(content)
            with open(filepath, 'w', encoding='utf-8-sig') as f:
                f.write("# This file is autogenerated by always_run.py\n")
                f.write("# Do not edit this file directly\n\n")
                f.write(yml_text)
